# Generated by Django 3.1.1 on 2020-12-25 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyers_ID', models.CharField(max_length=20)),
                ('commodities_ID', models.CharField(max_length=20)),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Commodities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodities_ID', models.CharField(max_length=20)),
                ('seller_ID', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('inventory', models.IntegerField()),
                ('state', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_ID', models.CharField(max_length=13)),
                ('telephone', models.CharField(max_length=13)),
                ('name', models.CharField(max_length=10)),
                ('sex', models.CharField(max_length=10)),
                ('college', models.CharField(max_length=20)),
                ('major', models.CharField(max_length=20)),
                ('dormitory', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_ID', models.CharField(max_length=20)),
                ('buyer_ID', models.CharField(max_length=20)),
                ('consignee', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('seller_ID', models.CharField(max_length=20)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('state', models.BooleanField(default=False)),
                ('commodities', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.commodities')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
